### ISSUE TITLE
Wasp

### ISSUE THREAD

**Issue by Abinsounderraj** [is-probably-gay/is-probably-gay#206]
### Subdomain Name

wasp.is-probably.gay

### DNS Record

https://abinsounderraj.github.io/wheather-app/

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by charlie-moomoo** [comment]
Do not edit the title

**Comment by Abinsounderraj** [comment]
> Do not edit the title
No domain?
