### ISSUE TITLE
🌈 Register ninad.is-probably.gay

### ISSUE THREAD

**Issue by charlie-moomoo** [is-probably-gay/is-probably-gay#214]
### Subdomain Name

ninad.is-probably.gay

### DNS Record

8.8.8.8

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by charlie-moomoo** [comment]
@ninadnaik10 I had removed that domain successfully.

**Comment by ninadnaik10** [comment]
Thank you so much for your quick action.
