### ISSUE TITLE
🌈 Register rldv1.is-probably.gay

### ISSUE THREAD

**Issue by YoutyaYoutyev** [is-probably-gay/is-probably-gay#332]
### Subdomain Name

rldv1.is-probably.gay

### DNS Record

185.17.3.231

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by rldv1** [comment]
гад

**Comment by nubovik01** [comment]
ору
