### ISSUE TITLE
penikmatmixue

### ISSUE THREAD

**Issue by aeshmm** [is-probably-gay/is-probably-gay#358]
### Subdomain Name

.is-probably.gay

### DNS Record

penikmatmixue.aternos.me

### Agreement

- [X] I have ensured that no one registered this subdomain
- [X] I have ensured that I did not reach the five subdomain limit

**Comment by playstation452** [comment]
bro is really trying to connect a mc server to his domain :skull:

**Comment by MagicTeaMC** [comment]
wrong format
